rules:
  - rule_id: 1
    rule_name: "Suspicious Port Scan"
    rule_description: "Detects if a source IP is scanning multiple ports on one or more destinations within a time window."
    rule_actions:
      - action: "email"
        email: "admin@example.com"
        template: "Suspicious Scan Detected: $(src_ip) is scanning $(dest_ip). Hit $(dest_port_count) unique ports in the last 60 seconds."
    rule_score: 5
    filter:
      - field: "data.flow.reason"
        operator: "eq"
        value: "timeout"
      - field: "data.tcp.rst"
        operator: "eq"
        value: "true"
    aggregation:
      type: "port_scan"
      time_window: 60
      group_by: "data.src_ip"
      unique_count_field: "data.dest_port"
      threshold: 5
