wazuh:
  host: "localhost"  # Replace with your Wazuh Indexer IP
  port: 9200
  username: "admin"  # Replace with your username
  password: "SecretPassword"  # Replace with your password
  
scheduler:
  interval_minutes: 1
  alert_fetch_size: 2000
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

smtp:
  server: "smtp.mailgun.org"
  port: 587
  user: "your_email@example.com"
  password: "your_email_password"
  from_email: "your_email@example.com"
